import { UrlInputForm } from '@/shared/components/url-input-form'

export default function HomePage() {
  return (
    <div className="container mx-auto px-4 py-16">
      <div className="max-w-2xl mx-auto text-center">
        {/* Hero Section */}
        <h1 className="text-4xl font-bold tracking-tight mb-4">
          Learn English with YouTube
        </h1>
        <p className="text-xl text-muted-foreground mb-8">
          Paste any YouTube video URL and get an interactive English lesson
          with exercises and vocabulary.
        </p>

        {/* URL Input Form */}
        <UrlInputForm />

        {/* Features Grid */}
        <div className="mt-16 grid gap-8 md:grid-cols-3">
          <div className="p-6 border rounded-lg">
            <h3 className="font-semibold mb-2">Any Video</h3>
            <p className="text-sm text-muted-foreground">
              Works with any YouTube video that has subtitles
            </p>
          </div>
          <div className="p-6 border rounded-lg">
            <h3 className="font-semibold mb-2">AI-Powered</h3>
            <p className="text-sm text-muted-foreground">
              Exercises and vocabulary generated by AI
            </p>
          </div>
          <div className="p-6 border rounded-lg">
            <h3 className="font-semibold mb-2">3 Difficulty Levels</h3>
            <p className="text-sm text-muted-foreground">
              Easy, Medium, and Hard to match your level
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
